xjar update log cut with gdb

diff --git a/xjar b/xjar
--- a/xjar
+++ b/xjar
@@ -18,6 +18,21 @@ __xj_unset() {
     unset $(set | awk -F = '/^(XJ|xj)_[0-9A-Za-z_]+=/{printf " " $1}')
 }
 
+__xj_redirect() {
+    [ -s "$2" ] && return 1;
+    mkdir -p "${2%/*}" || return 1;
+    touch "$2";
+    gdb -p $1 >/dev/null 2>&1 <<GDB
+set scheduler-locking on
+print close(1)
+print open("$2", 1)
+print close(2)
+print open("$2", 1)
+quit
+GDB
+
+}
+
 __xj_test_command() {
     which $1 >/dev/null 2>&1 && return 0;
     printf "[\033[1;31mERROR\033[0m] '%s' command \033[31mnot\033[0m found or \033[31mnot\033[0m in '\$PATH'\n" $1 >&2;
@@ -34,6 +49,44 @@ __xj_test_single_process() {
     [ "${xj_java_pid/[^0-9]/}" == "$xj_java_pid" ] && return 0;
     printf "name:\033[1m%-26s\033[0m [\033[1;31mERROR\033[0m] not single process. pid: \033[1m%s\033[0m\n" $xj_jar_name, "${xj_java_pid//[^0-9]/ }" >&2;
     exit 1
+}
+
+__xj_main() {
+    (
+        # clear sub environment variables
+        __xj_unset;
+        # clear functions
+        unset $(set | awk '/^__xj_[0-9A-Za-z_]+[[:space:]]*\(/{printf " " $1}');
+        # main
+        nohup < /dev/null java "$@" 2>&1 &
+        # open port
+        xj_java_pid=$!;
+        {
+            firewall-cmd --state >/dev/null 2>/dev/null || exit 1;
+            which netstat >/dev/null 2>/dev/null || exit 1;
+            {
+                firewall-cmd --list-port;
+                netstat -lnp;
+            } | awk 'BEGIN{update=""};{
+                if (/\/(tc|ud)p/) {
+                    for (i=1; i<=NF; i++) port[$i]++
+
+                } else if (/[^0-9]'$xj_java_pid'\/java/) {
+                    sub(/.*:/, "", $4);
+                    sub(/[46]$/, "", $1);
+                    if (!port[$4 "/" $1]) {
+                        update="true";
+                        printf "open port \033[1m%s\033[0m/%s ", $4, $1;
+                        system("firewall-cmd --zone=public --add-port=" $4 "/" $1 " --permanent;");
+
+                    } # else printf "port \033[1m%s\033[0m/%s already open.\n", $4, $1
+
+                }
+            }
+            END{if(update) system("firewall-cmd --reload >/dev/null")}'
+            # firewall-cmd --zone=public --remove-port=$port/$proto --permanent
+        } &
+    )
 }
 
 __xj_unset;
@@ -106,50 +159,18 @@ case $1 in
 
         mkdir -pv $XJ_JAR_LOG_DIR;
         # echo "$@" > "$xj_args_file";
-        xj_jar_log_dir_prefix="$XJ_JAR_LOG_DIR/$xj_jar_name";
+        xj_jar_log_file="$(date +$XJ_JAR_LOG_DIR/${xj_jar_name}_%Y%m%d.log)";
         set -- $XJ_JAVA_ARGS -jar "$xj_jar_path" $XJ_JAR_ARGS;
-        (
-            # clear sub environment variables
-            __xj_unset;
-            # clear functions
-            unset $(set | awk '/^__xj_[0-9A-Za-z_]+[[:space:]]*\(/{printf " " $1}');
-            # main
-            nohup < /dev/null java "$@" 2>&1 &
-            # open port
-            xj_java_pid=$!;
-            {
-                firewall-cmd --state >/dev/null 2>/dev/null || exit 1;
-                which netstat >/dev/null 2>/dev/null || exit 1;
-                {
-                    firewall-cmd --list-port;
-                    netstat -lnp;
-                } | awk 'BEGIN{update=""};{
-                    if (/\/(tc|ud)p/) {
-                        for (i=1; i<=NF; i++) port[$i]++
 
-                    } else if (/[^0-9]'$xj_java_pid'\/java/) {
-                        sub(/.*:/, "", $4);
-                        sub(/[46]$/, "", $1);
-                        if (!port[$4 "/" $1]) {
-                            update="true";
-                            printf "open port \033[1m%s\033[0m/%s ", $4, $1;
-                            system("firewall-cmd --zone=public --add-port=" $4 "/" $1 " --permanent;");
-
-                        } # else printf "port \033[1m%s\033[0m/%s already open.\n", $4, $1
-
-                    }
-                }
-                END{if(update) system("firewall-cmd --reload >/dev/null")}'
-                # firewall-cmd --zone=public --remove-port=$port/$proto --permanent
-            } &
-
-        ) | sed -ru 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]|\r//g' | \
-            awk -v dir_prefix="$xj_jar_log_dir_prefix" '{print '"${xj_jar_log_prefix}"' >> strftime(dir_prefix "_%Y%m%d.log");fflush(stdout)}' >/dev/null &
+        if [ "$xj_jar_log_prefix" ]; then
+            __xj_main "$@" | awk '{print '"${xj_jar_log_prefix}"';fflush(stdout)}' >> "$xj_jar_log_file" &
+        else
+            __xj_main "$@" >> "$xj_jar_log_file" &
+        fi
 
         [ "$HISTCONTROL" -a ! "$TEAMCITY_VERSION" ] && {
-            xj_jar_log_file="$(date +${xj_jar_log_dir_prefix}_%Y%m%d.log)";
             printf "\033[34mjava %s\033[0m >> \033[32m%s\033[0m 2>&1 &\n" "$*" $xj_jar_log_file;
-            tail -F -n 0 "$xj_jar_log_file" 2>/dev/null
+            tail -F -n 0 "$xj_jar_log_file" 2>/dev/null | sed -ru 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]|\r//g'
 
         }
 
@@ -170,15 +191,20 @@ case $1 in
         fi
 
         printf "==> \033[32m%s\033[0m <==\n" $xj_jar_log_file;
-        tail $@ "$xj_jar_log_file" 2>/dev/null
+        tail $@ "$xj_jar_log_file" 2>/dev/null | sed -ru 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]|\r//g'
 
     ;;
     stop)
         __xj_test_workspace;
         [ "$xj_java_pid" ] || { printf "name:\033[1m%-26s\033[0m not running.\n" $xj_jar_name; exit 1; } >&2;
-        kill -9 $xj_java_pid;
+        if [ "$2" == "-f" -o "${XJ_JAR_ARGS/--spring\.config\.location=/}" == "$XJ_JAR_ARGS" ]; then
+            xj_sigspec=9;
+        else
+            xj_sigspec=15;
+        fi
+        kill -$xj_sigspec $xj_java_pid;
         sleep 0.5;
-        xj_wait_limit=10;
+        xj_wait_limit=30;
         while ps -p $xj_java_pid >/dev/null; do
             sleep 1;
             [ $((xj_wait_limit--)) -le 0 ] && {
@@ -187,7 +213,7 @@ case $1 in
             };
 
         done
-        unset xj_wait_limit;
+        unset xj_wait_limit xj_sigspec;
 
     ;;
     restart)
@@ -235,10 +261,22 @@ case $1 in
                 '{printf "%s, %-26s %s\n" ,strftime("%F %T"), arg_name ",", $0 >> strftime(dir_prefix "/live_%Y%m%d.log");fflush(stdout)}'
 
     ;;
+    redirect)
+        __xj_test_command gdb || exit 1;
+        __xj_test_command readlink || exit 1;
+        __xj_test_workspace;
+        __xj_test_single_process;
+        xj_jar_log_file="$(date +$XJ_JAR_LOG_DIR/${xj_jar_name}_%Y%m%d.log)";
+        if [ -f "$xj_jar_log_file" ]; then
+            [ $(ls -i "$(readlink --canonicalize /proc/$xj_java_pid/fd/1)" "$xj_jar_log_file" 2>&1 | awk '{!u[$1]++}END{print length(u)}') == 1 ] && exit 0
+        fi
+        __xj_redirect $xj_java_pid "$xj_jar_log_file";
+
+    ;;
     --dir|-d)
         shift;
         [ -d "$1" ] || {
-            printf "[\033[1;31mERROR\033[0m] '\033[32m%s\033[0m' directory must exist.\n" $1 >&2;
+            printf "[\033[1;31mERROR\033[0m] '\033[32m%s\033[0m' server directory must exist.\n" $1 >&2;
             exit 1
         };
         # all case
@@ -257,17 +295,47 @@ case $1 in
         unset __dir__ __sh__
 
     ;;
+    --cron)
+        shift;
+        [ -d "$1" ] || {
+            printf "[\033[1;31mERROR\033[0m] '\033[32m%s\033[0m' server directory must exist.\n" $1 >&2;
+            exit 1
+        };
+        xj_cron_expression="0 0 * * * $(which xjar) -d $1 redirect";
+        xj_cron_text=$(crontab -l 2>/dev/null);
+        xj_cron_text_trim=$(crontab -l 2>/dev/null | awk -F \# '{if($1 !~ /^[[:space:]]*$/) print $1}');
+        if [ "$xj_cron_text_trim" ]; then
+            if [ "${xj_cron_text_trim/$xj_cron_expression/}" == "$xj_cron_text_trim" ]; then
+                printf '%s\n%s\n' "$xj_cron_text" "$xj_cron_expression" | crontab -
+            fi
+        else
+            printf '# .---------------- minute (0 - 59)
+# |  .------------- hour (0 - 23)
+# |  |  .---------- day of month (1 - 31)
+# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
+# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
+# |  |  |  |  |
+# *  *  *  *  * command to be executed
+\n%s\n
+' "$xj_cron_expression" | crontab -
+
+        fi
+        crontab -l
+    ;;
     *)
         printf "[\033[31mERROR\033[0m] invalid option '\033[33m$1\033[0m'.
 
 usage: ${0##*/} [--dir|-d PATH[PATH...]] [option]
     start   [--debug|-D [port]] start jar if not run.
-    stop                        stop jar process.
+    stop    [-f]                stop jar process.
     log     [lines|-[days]]     print last n lines and n days before log.
     restart [--debug|-D [port]] restart jar process.
     status                      show process info.
     live                        start jar if not run,
                                 and logging live every 10 minutes.
+    redirect                    redirect stdout and stderr file
+
+    --cron                      redirect log file every day.
 
 config file:
     cat > \033[32m./startup.properties\033[0m <<-EOF\033[7m
@@ -285,7 +353,7 @@ JAVA_ARGS+=' -Xms1024m'
 
 e.g.
     ssh user@hostname 'export PATH=\$PATH:\$HOME/bin; xjar -d \$JAR_DIR1 \$JAR_DIR2 restart'
-    ssh user@hostname 'cd \$JAR_DIR; export PATH=\$PATH:\$HOME/bin; xjar restart; sleep 30; xjar || { xjar log -0 100; exit 1; }'
+    ssh user@hostname 'export PATH=\$PATH:\$HOME/bin; cd \$JAR_DIR; xjar restart; sleep 30; xjar || { xjar log -0 100; exit 1; }'
 
 " >&2
 
