xjar update redirect

diff --git a/xjar b/xjar
--- a/xjar
+++ b/xjar
@@ -268,9 +268,15 @@ case $1 in
         __xj_test_single_process;
         xj_jar_log_file="$(date +$XJ_JAR_LOG_DIR/${xj_jar_name}_%Y%m%d.log)";
         if [ -f "$xj_jar_log_file" ]; then
-            [ $(ls -i "$(readlink --canonicalize /proc/$xj_java_pid/fd/1)" "$xj_jar_log_file" 2>&1 | awk '{!u[$1]++}END{print length(u)}') == 1 ] && exit 0
+            [ $(ls -i "$(readlink --canonicalize /proc/$xj_java_pid/fd/1)" "$xj_jar_log_file" 2>&1 | awk '{!u[$1]++}END{print length(u)}') == 1 ] && {
+                printf "[\033[1;31mERROR\033[0m] '\033[32m%s\033[0m' source log and target log are the same file.\n" $1 >&2;
+                exit 1
+            }
         fi
-        __xj_redirect $xj_java_pid "$xj_jar_log_file";
+        __xj_redirect $xj_java_pid "$xj_jar_log_file" || {
+            printf "[\033[1;31mERROR\033[0m] '\033[32m%s\033[0m' target log file not empty.\n" $1 >&2;
+            exit 1
+        }
 
     ;;
     --dir|-d)
