fix xjar redirect for awk

diff --git a/xjar b/xjar
--- a/xjar
+++ b/xjar
@@ -264,17 +264,25 @@ case $1 in
     redirect)
         __xj_test_command gdb || exit 1;
         __xj_test_command readlink || exit 1;
+        [ "$xj_java_pid" ] || {
+            printf "name:\033[1m%-26s\033[0m [\033[1;31mERROR\033[0m] not running.\n" $xj_jar_name, >&2;
+            exit 1
+        };
         __xj_test_workspace;
         __xj_test_single_process;
         xj_jar_log_file="$(date +$XJ_JAR_LOG_DIR/${xj_jar_name}_%Y%m%d.log)";
-        if [ -f "$xj_jar_log_file" ]; then
-            [ $(ls -i "$(readlink --canonicalize /proc/$xj_java_pid/fd/1)" "$xj_jar_log_file" 2>&1 | awk '{!u[$1]++}END{print length(u)}') == 1 ] && {
-                printf "[\033[1;31mERROR\033[0m] source log and target log are the same file.\n" >&2;
-                exit 1
-            }
+        xj_java_fd="$(readlink --canonicalize /proc/$xj_java_pid/fd/1)";
+        xj_pid=$xj_java_pid;
+        if [ "${xj_java_fd/\/pipe:\[/}" != "$xj_java_fd" ]; then
+            while read xj_awk_pid xj_awk_pipe; do
+                [ "${xj_java_fd%"$xj_awk_pipe"}" == "$xj_java_fd" ] || {
+                    xj_pid=$xj_awk_pid;
+                    break
+                };
+            done < <(ps -ef | awk '/strftime\(/{system("readlink --canonicalize /proc/" $2 "/fd/0")}' | awk -F '/' '{print $3, $5}')
         fi
-        __xj_redirect $xj_java_pid "$xj_jar_log_file" || {
-            printf "[\033[1;31mERROR\033[0m] target log file not empty.\n" >&2;
+        __xj_redirect $xj_pid "$xj_jar_log_file" || {
+            printf "name:\033[1m%-26s\033[0m [\033[1;31mERROR\033[0m] target log file '$xj_jar_log_file' exist and not empty.\n" $xj_jar_name, >&2;
             exit 1
         }
 
